version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errchkjson
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - modernize
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - encoding/json.Marshal
        - encoding/json.MarshalIndent
    revive:
      rules:
        - name: var-naming
          exclude:
            [
              "**/internal/server/api.go",
              "**/internal/api/**",
              "**/internal/util/**",
            ]
  exclusions:
    generated: lax
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kibirisu
  exclusions:
    generated: lax
