version: "2"
sql:
  - engine: "postgresql"
    queries: "internal/db/query.sql"
    schema: "internal/db/migrations"
    gen:
      go:
        package: "db"
        out: "internal/db"
        overrides:
          - db_type: "pg_catalog.varchar"
            go_type:
              type: "ID"
              import: "github.com/rs/xid"
          - column: "statuses.in_reply_to_id"
            go_type:
              type: "ID"
              import: "github.com/rs/xid"
              pointer: true
          - column: "statuses.in_reply_to_account_id"
            go_type:
              type: "ID"
              import: "github.com/rs/xid"
              pointer: true
          - column: "statuses.reblog_of_id"
            go_type:
              type: "ID"
              import: "github.com/rs/xid"
              pointer: true
          - column: "statuses.reblog_of_account_id"
            go_type:
              type: "ID"
              import: "github.com/rs/xid"
              pointer: true
