x-borg-default: &borg
  build: .
  networks:
    - net

x-db-default: &db
  image: postgres:18-alpine
  networks:
    - net
  environment:
    - POSTGRES_DB=borg
    - POSTGRES_USER=borg
    - POSTGRES_PASSWORD=borg
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U borg"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  app-alice:
    <<: *borg
    container_name: app-alice
    environment:
      - DATABASE_URL=postgres://borg:borg@db-alice:5432/borg?sslmode=disable
      - ADDRESS=borg-alice
    depends_on:
      db-alice:
        condition: service_healthy
  db-alice:
    <<: *db
    container_name: db-alice
    volumes:
      - db-data-alice:/var/lib/postgresql

  app-bob:
    <<: *borg
    container_name: app-bob
    environment:
      - DATABASE_URL=postgres://borg:borg@db-bob:5432/borg?sslmode=disable
      - ADDRESS=borg-bob
    depends_on:
      db-bob:
        condition: service_healthy
  db-bob:
    <<: *db
    container_name: db-bob
    volumes:
      - db-data-bob:/var/lib/postgresql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    networks:
      net:
        aliases:
          - borg-alice
          - borg-bob
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-alice
      - app-bob

networks:
  net:
    driver: bridge

volumes:
  db-data-alice:
  db-data-bob:
