// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Account defines model for Account.
type Account struct {
	Acct        string `json:"acct"`
	DisplayName string `json:"displayName"`
	Id          int    `json:"id"`
	Url         string `json:"url"`
	Username    string `json:"username"`
}

// AuthForm defines model for AuthForm.
type AuthForm struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Comment defines model for Comment.
type Comment struct {
	UpdatedAt time.Time `json:"UpdatedAt"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	ParentID  int       `json:"parentID"`
	PostID    int       `json:"postID"`
	UserID    int       `json:"userID"`
}

// Like defines model for Like.
type Like struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	PostID    int       `json:"postID"`
	UserID    int       `json:"userID"`
}

// NewComment defines model for NewComment.
type NewComment struct {
	Content string `json:"content"`
	PostID  int    `json:"postID"`
	UserID  int    `json:"userID"`
}

// NewLike defines model for NewLike.
type NewLike struct {
	PostID int `json:"postID"`
	UserID int `json:"userID"`
}

// NewPost defines model for NewPost.
type NewPost struct {
	Content string `json:"content"`
	UserID  int    `json:"userID"`
}

// NewShare defines model for NewShare.
type NewShare struct {
	PostID int `json:"postID"`
	UserID int `json:"userID"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Post defines model for Post.
type Post struct {
	CommentCount int       `json:"commentCount"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           int       `json:"id"`
	LikeCount    int       `json:"likeCount"`
	ShareCount   int       `json:"shareCount"`
	UpdatedAt    time.Time `json:"updatedAt"`
	UserID       int       `json:"userID"`
	Username     *string   `json:"username,omitempty"`
}

// Share defines model for Share.
type Share struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	PostID    int       `json:"postID"`
	UserID    int       `json:"userID"`
}

// UpdatePost defines model for UpdatePost.
type UpdatePost struct {
	Content *string `json:"content,omitempty"`
}

// UpdateUser defines model for UpdateUser.
type UpdateUser struct {
	Bio     *string `json:"bio,omitempty"`
	IsAdmin *bool   `json:"isAdmin,omitempty"`
}

// User defines model for User.
type User struct {
	Bio            string    `json:"bio"`
	CreatedAt      time.Time `json:"createdAt"`
	FollowersCount int       `json:"followersCount"`
	FollowingCount int       `json:"followingCount"`
	Id             int       `json:"id"`
	IsAdmin        bool      `json:"isAdmin"`
	Origin         string    `json:"origin"`
	UpdatedAt      time.Time `json:"updatedAt"`
	Username       string    `json:"username"`
}

// WebFingerLink defines model for WebFingerLink.
type WebFingerLink struct {
	Href string `json:"href"`
	Rel  string `json:"rel"`
	Type string `json:"type"`
}

// WebFingerResponse defines model for WebFingerResponse.
type WebFingerResponse struct {
	Links   []WebFingerLink `json:"links"`
	Subject string          `json:"subject"`
}

// GetWellKnownWebfingerParams defines parameters for GetWellKnownWebfinger.
type GetWellKnownWebfingerParams struct {
	Resource string `form:"resource" json:"resource"`
}

// GetApiAccountsLookupParams defines parameters for GetApiAccountsLookup.
type GetApiAccountsLookupParams struct {
	Acct string `form:"acct" json:"acct"`
}

// PostApiPostsJSONRequestBody defines body for PostApiPosts for application/json ContentType.
type PostApiPostsJSONRequestBody = NewPost

// PutApiPostsIdJSONRequestBody defines body for PutApiPostsId for application/json ContentType.
type PutApiPostsIdJSONRequestBody = UpdatePost

// PostApiPostsIdCommentsJSONRequestBody defines body for PostApiPostsIdComments for application/json ContentType.
type PostApiPostsIdCommentsJSONRequestBody = NewComment

// PostApiPostsIdLikesJSONRequestBody defines body for PostApiPostsIdLikes for application/json ContentType.
type PostApiPostsIdLikesJSONRequestBody = NewLike

// PostApiPostsIdSharesJSONRequestBody defines body for PostApiPostsIdShares for application/json ContentType.
type PostApiPostsIdSharesJSONRequestBody = NewShare

// PostApiUsersJSONRequestBody defines body for PostApiUsers for application/json ContentType.
type PostApiUsersJSONRequestBody = NewUser

// PutApiUsersIdJSONRequestBody defines body for PutApiUsersId for application/json ContentType.
type PutApiUsersIdJSONRequestBody = UpdateUser

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthForm

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = AuthForm

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get WebFinger
	// (GET /.well-known/webfinger)
	GetWellKnownWebfinger(w http.ResponseWriter, r *http.Request, params GetWellKnownWebfingerParams)
	// Look up a user
	// (GET /api/accounts/lookup)
	GetApiAccountsLookup(w http.ResponseWriter, r *http.Request, params GetApiAccountsLookupParams)
	// Follow a user
	// (POST /api/accounts/{id}/follow)
	PostApiAccountsIdFollow(w http.ResponseWriter, r *http.Request, id int)
	// Get all posts
	// (GET /api/posts)
	GetApiPosts(w http.ResponseWriter, r *http.Request)
	// Create a post
	// (POST /api/posts)
	PostApiPosts(w http.ResponseWriter, r *http.Request)
	// Delete a post by ID
	// (DELETE /api/posts/{id})
	DeleteApiPostsId(w http.ResponseWriter, r *http.Request, id int)
	// Get a post by ID
	// (GET /api/posts/{id})
	GetApiPostsId(w http.ResponseWriter, r *http.Request, id int)
	// Update a post
	// (PUT /api/posts/{id})
	PutApiPostsId(w http.ResponseWriter, r *http.Request, id int)
	// Get a post's comments by ID
	// (GET /api/posts/{id}/comments)
	GetApiPostsIdComments(w http.ResponseWriter, r *http.Request, id int)
	// Create a post comment
	// (POST /api/posts/{id}/comments)
	PostApiPostsIdComments(w http.ResponseWriter, r *http.Request, id int)
	// Get post's likes
	// (GET /api/posts/{id}/likes)
	GetApiPostsIdLikes(w http.ResponseWriter, r *http.Request, id int)
	// Create a post like
	// (POST /api/posts/{id}/likes)
	PostApiPostsIdLikes(w http.ResponseWriter, r *http.Request, id int)
	// Get post's shares
	// (GET /api/posts/{id}/shares)
	GetApiPostsIdShares(w http.ResponseWriter, r *http.Request, id int)
	// Create a post share
	// (POST /api/posts/{id}/shares)
	PostApiPostsIdShares(w http.ResponseWriter, r *http.Request, id int)
	// Delete a comment by ID
	// (DELETE /api/posts/{postId}/comments/{commentId})
	DeleteApiPostsPostIdCommentsCommentId(w http.ResponseWriter, r *http.Request, postId int, commentId int)
	// Create a user
	// (POST /api/users)
	PostApiUsers(w http.ResponseWriter, r *http.Request)
	// Delete a user by ID
	// (DELETE /api/users/{id})
	DeleteApiUsersId(w http.ResponseWriter, r *http.Request, id int)
	// Get a user by ID
	// (GET /api/users/{id})
	GetApiUsersId(w http.ResponseWriter, r *http.Request, id int)
	// Update a user
	// (PUT /api/users/{id})
	PutApiUsersId(w http.ResponseWriter, r *http.Request, id int)
	// Get liked posts of user with ID
	// (GET /api/users/{id}/favourites)
	GetApiUsersIdFavourites(w http.ResponseWriter, r *http.Request, id int)
	// Get followers of the user with ID
	// (GET /api/users/{id}/followers)
	GetApiUsersIdFollowers(w http.ResponseWriter, r *http.Request, id int)
	// Get followed of the user with ID
	// (GET /api/users/{id}/following)
	GetApiUsersIdFollowing(w http.ResponseWriter, r *http.Request, id int)
	// Get posts of user with ID
	// (GET /api/users/{id}/posts)
	GetApiUsersIdPosts(w http.ResponseWriter, r *http.Request, id int)
	// Get shared posts of user with ID
	// (GET /api/users/{id}/reblogged)
	GetApiUsersIdReblogged(w http.ResponseWriter, r *http.Request, id int)
	// Get timeline posts of the user with ID (posts from followed users)
	// (GET /api/users/{id}/timeline)
	GetApiUsersIdTimeline(w http.ResponseWriter, r *http.Request, id int)
	// Login the user
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Register the user
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get WebFinger
// (GET /.well-known/webfinger)
func (_ Unimplemented) GetWellKnownWebfinger(w http.ResponseWriter, r *http.Request, params GetWellKnownWebfingerParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Look up a user
// (GET /api/accounts/lookup)
func (_ Unimplemented) GetApiAccountsLookup(w http.ResponseWriter, r *http.Request, params GetApiAccountsLookupParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Follow a user
// (POST /api/accounts/{id}/follow)
func (_ Unimplemented) PostApiAccountsIdFollow(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all posts
// (GET /api/posts)
func (_ Unimplemented) GetApiPosts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a post
// (POST /api/posts)
func (_ Unimplemented) PostApiPosts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a post by ID
// (DELETE /api/posts/{id})
func (_ Unimplemented) DeleteApiPostsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a post by ID
// (GET /api/posts/{id})
func (_ Unimplemented) GetApiPostsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a post
// (PUT /api/posts/{id})
func (_ Unimplemented) PutApiPostsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a post's comments by ID
// (GET /api/posts/{id}/comments)
func (_ Unimplemented) GetApiPostsIdComments(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a post comment
// (POST /api/posts/{id}/comments)
func (_ Unimplemented) PostApiPostsIdComments(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get post's likes
// (GET /api/posts/{id}/likes)
func (_ Unimplemented) GetApiPostsIdLikes(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a post like
// (POST /api/posts/{id}/likes)
func (_ Unimplemented) PostApiPostsIdLikes(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get post's shares
// (GET /api/posts/{id}/shares)
func (_ Unimplemented) GetApiPostsIdShares(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a post share
// (POST /api/posts/{id}/shares)
func (_ Unimplemented) PostApiPostsIdShares(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a comment by ID
// (DELETE /api/posts/{postId}/comments/{commentId})
func (_ Unimplemented) DeleteApiPostsPostIdCommentsCommentId(w http.ResponseWriter, r *http.Request, postId int, commentId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a user
// (POST /api/users)
func (_ Unimplemented) PostApiUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a user by ID
// (DELETE /api/users/{id})
func (_ Unimplemented) DeleteApiUsersId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user by ID
// (GET /api/users/{id})
func (_ Unimplemented) GetApiUsersId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a user
// (PUT /api/users/{id})
func (_ Unimplemented) PutApiUsersId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get liked posts of user with ID
// (GET /api/users/{id}/favourites)
func (_ Unimplemented) GetApiUsersIdFavourites(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get followers of the user with ID
// (GET /api/users/{id}/followers)
func (_ Unimplemented) GetApiUsersIdFollowers(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get followed of the user with ID
// (GET /api/users/{id}/following)
func (_ Unimplemented) GetApiUsersIdFollowing(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get posts of user with ID
// (GET /api/users/{id}/posts)
func (_ Unimplemented) GetApiUsersIdPosts(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get shared posts of user with ID
// (GET /api/users/{id}/reblogged)
func (_ Unimplemented) GetApiUsersIdReblogged(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get timeline posts of the user with ID (posts from followed users)
// (GET /api/users/{id}/timeline)
func (_ Unimplemented) GetApiUsersIdTimeline(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login the user
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register the user
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetWellKnownWebfinger operation middleware
func (siw *ServerInterfaceWrapper) GetWellKnownWebfinger(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWellKnownWebfingerParams

	// ------------- Required query parameter "resource" -------------

	if paramValue := r.URL.Query().Get("resource"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resource"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "resource", r.URL.Query(), &params.Resource)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWellKnownWebfinger(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAccountsLookup operation middleware
func (siw *ServerInterfaceWrapper) GetApiAccountsLookup(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiAccountsLookupParams

	// ------------- Required query parameter "acct" -------------

	if paramValue := r.URL.Query().Get("acct"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "acct"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "acct", r.URL.Query(), &params.Acct)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "acct", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAccountsLookup(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiAccountsIdFollow operation middleware
func (siw *ServerInterfaceWrapper) PostApiAccountsIdFollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiAccountsIdFollow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPosts operation middleware
func (siw *ServerInterfaceWrapper) GetApiPosts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPosts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiPosts operation middleware
func (siw *ServerInterfaceWrapper) PostApiPosts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiPosts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiPostsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiPostsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiPostsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPostsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiPostsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPostsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiPostsId operation middleware
func (siw *ServerInterfaceWrapper) PutApiPostsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiPostsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPostsIdComments operation middleware
func (siw *ServerInterfaceWrapper) GetApiPostsIdComments(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPostsIdComments(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiPostsIdComments operation middleware
func (siw *ServerInterfaceWrapper) PostApiPostsIdComments(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiPostsIdComments(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPostsIdLikes operation middleware
func (siw *ServerInterfaceWrapper) GetApiPostsIdLikes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPostsIdLikes(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiPostsIdLikes operation middleware
func (siw *ServerInterfaceWrapper) PostApiPostsIdLikes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiPostsIdLikes(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPostsIdShares operation middleware
func (siw *ServerInterfaceWrapper) GetApiPostsIdShares(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPostsIdShares(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiPostsIdShares operation middleware
func (siw *ServerInterfaceWrapper) PostApiPostsIdShares(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiPostsIdShares(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiPostsPostIdCommentsCommentId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiPostsPostIdCommentsCommentId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "postId" -------------
	var postId int

	err = runtime.BindStyledParameterWithOptions("simple", "postId", chi.URLParam(r, "postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	// ------------- Path parameter "commentId" -------------
	var commentId int

	err = runtime.BindStyledParameterWithOptions("simple", "commentId", chi.URLParam(r, "commentId"), &commentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "commentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiPostsPostIdCommentsCommentId(w, r, postId, commentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiUsers operation middleware
func (siw *ServerInterfaceWrapper) PostApiUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiUsersId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiUsersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiUsersId operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiUsersId operation middleware
func (siw *ServerInterfaceWrapper) PutApiUsersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiUsersIdFavourites operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsersIdFavourites(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiUsersIdFavourites(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiUsersIdFollowers operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsersIdFollowers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiUsersIdFollowers(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiUsersIdFollowing operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsersIdFollowing(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiUsersIdFollowing(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiUsersIdPosts operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsersIdPosts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiUsersIdPosts(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiUsersIdReblogged operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsersIdReblogged(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiUsersIdReblogged(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiUsersIdTimeline operation middleware
func (siw *ServerInterfaceWrapper) GetApiUsersIdTimeline(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiUsersIdTimeline(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/.well-known/webfinger", wrapper.GetWellKnownWebfinger)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/accounts/lookup", wrapper.GetApiAccountsLookup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/accounts/{id}/follow", wrapper.PostApiAccountsIdFollow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/posts", wrapper.GetApiPosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/posts", wrapper.PostApiPosts)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/posts/{id}", wrapper.DeleteApiPostsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/posts/{id}", wrapper.GetApiPostsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/posts/{id}", wrapper.PutApiPostsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/posts/{id}/comments", wrapper.GetApiPostsIdComments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/posts/{id}/comments", wrapper.PostApiPostsIdComments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/posts/{id}/likes", wrapper.GetApiPostsIdLikes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/posts/{id}/likes", wrapper.PostApiPostsIdLikes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/posts/{id}/shares", wrapper.GetApiPostsIdShares)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/posts/{id}/shares", wrapper.PostApiPostsIdShares)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/posts/{postId}/comments/{commentId}", wrapper.DeleteApiPostsPostIdCommentsCommentId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/users", wrapper.PostApiUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/users/{id}", wrapper.DeleteApiUsersId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users/{id}", wrapper.GetApiUsersId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/users/{id}", wrapper.PutApiUsersId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users/{id}/favourites", wrapper.GetApiUsersIdFavourites)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users/{id}/followers", wrapper.GetApiUsersIdFollowers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users/{id}/following", wrapper.GetApiUsersIdFollowing)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users/{id}/posts", wrapper.GetApiUsersIdPosts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users/{id}/reblogged", wrapper.GetApiUsersIdReblogged)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users/{id}/timeline", wrapper.GetApiUsersIdTimeline)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RaW2/buBL+KwLPAc5ZrFulu/vkNzdFFt4GbdA0yEPRB1oay6wpUiWpGkbg/77gRTfr",
	"YtqJ3M3mTRFH5Mw3Hz/OMH5AEU8zzoApiaYPSEYrSLF5nEURz5nSj5ngGQhFwAzgKDJv1TYDNEVSCcIS",
	"tJugmMiM4u0HnELnOIlrrwlTkIDQ73NBO+1zCYJ1T7abIAHfcyIgRtMveuaa+cS62HTILvN1UszEF98g",
	"UnqZWa5WV1yk7UgzLOWGi/iR3tUcK2fscuSSpyl0IX6XxVhBPDNDSy5SrNAU6XevFDHztryLOFNurvaY",
	"gGOn60tdhgUwNX/XM8pl75gGpXusK7dupvKzKsCaD/XIJjXQurC+JmtoA/2UyIwZe+lmV2gfYNPLpCFa",
	"PInH/YnqcbU7EaP40uPBDZdHIuXtgS8ItyssfjIKdxLET1fAvlQYNl8Wx1EbjDOpHSVrGPBC6iwOjOfH",
	"y3h/lk86HveUs4qn4fykiXhTVvNBWe0h8r9CV+2Bcqxa7Hpn6t5xC8K7iyc5i1PCamMLzilg1rPEUZOf",
	"kJ8lp5RvQMgBwlsbwpIBm748D8Q7QVyQpDFW2zGnbbLT6kyNZ+lN5XMLnRYUx+ype1hcEZaAuCZs3c7p",
	"SsCyEwkB3WW1fXEoVP21s53YNQZ9+wQy40x27H1K2No8EAWpefiv8Rj9J6x6j9A1HmEz2IrZWAi8NSKb",
	"28UPBlAYTpwHbff1bBDlgqjtrV7e+vsWsAChmwKzY8xfVwWP/rr/rLXSWKOps604tVIqQzs9MWFLXggD",
	"Nu7qBglkJEimCGf6Yy6S4GMGbHYzD2QGEVmSCJvBCVJEUSiMZjdzNEE/QEj75cXri9dvzD7IgOGMoCn6",
	"3bzSx6tamTDC1xug9NWa8Q0LN7BYGlT1SAIGPZ0js9o8RlP0J6h7oPS9Nr8vrU1xjVNQICSafnlAetOh",
	"7zmILZogu2eQAMlzEWmeVPgrkYMDCnfl6qs2tpQx7v52cbGnozjLqMMj/CbiX79JzqoW1ZtHJTFNWpoZ",
	"+PjekiBPUyy2FoWg/NKMhTgjIbatsAwp5+s8GwJxlhHXOMtra+yFoWtYR8PvKOyKzr8DsSueszhQKwi0",
	"Cu6hpwMO8izA1WATvgcS70KrhEV52wZRH7A1FOfxlf2gG0fN9wpGo88HQayqgh4U92M2Wh4HMo8ikHKZ",
	"U7ptqIdxp64bX77qqStk7BQtYDQA8gCbbozNI7PtJb2msmkprueuwZQGNhxXo/Umtgroew5SveXx9smY",
	"W3Rzu+ZhoHmwa0DIckqPyN+lOawDbELcy59htWUNBQXtuN+Z90Xk8/hMTP6jzWTrSReRy0itiYs0WGyD",
	"+Tud0UMEPVtUT6dyFVF86L2HR5Z3ETw/Cx5Pv21qnc3BndMjku62retYsEMDmyd07aaXFM7jy8L6n8g4",
	"L6UtrudOFlsD5f9kUABXI+ZB6T0HgKMoe4namOJeQNrJU0rW4EnSa2P6bBlqbmVPpacjp0XLk5Mj4zUK",
	"IS1Io7KR2iXaVDTXdZ5cvLW2z5aM9lLxkWx0gHnScWzIRuGjw2lUQkq3RpOR5iq1dpCHD+5pfkxpfGNm",
	"KU6ny2IGryxYD47LxKRzpqi27vkKcN9slPW5c7M4+YuE6PpLHmyu74zVaES8s0WgRyX5po2R5VtnJVlS",
	"sdlGm5j92zAT/HNpw3RsXm3YeaN6ujas4opX4dvEY6ANGx2Psdow/81zYhvWt3nCJf7BtQodrCsctleV",
	"/bOtLR516aWrs9heewV8abm5IWrVVuT61acTaA98S/NnC68l84nwlnBpcIs7Zw+ACUuOAVibv2iAY298",
	"fS6sHbbFNe9L1AV/RRCwoDxJIPYD9VNp/jKBNd3HMYqrSAqUMPCD93Nh/TLRLcCq8N0XheD/dmgpeFqp",
	"h8H7F4d/rlYh5e7XGQNNSK5W19z+bGKMWqr8Ue+pldRtrTgPJEkYxAFhrf94JoQ1/x1qERCQEKncT3AG",
	"QfhUWD4jHPJsD4ciiDoUu93fAQAA//9AMharXS4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
