// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Account defines model for Account.
type Account struct {
	Acct           string `json:"acct"`
	DisplayName    string `json:"display_name"`
	FollowersCount int    `json:"followers_count"`
	FollowingCount int    `json:"following_count"`
	Id             string `json:"id"`
	Url            string `json:"url"`
	Username       string `json:"username"`
}

// AuthForm defines model for AuthForm.
type AuthForm struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Status defines model for Status.
type Status struct {
	Account            Account `json:"account"`
	Content            string  `json:"content"`
	Favourited         *bool   `json:"favourited,omitempty"`
	FavouritesCount    int     `json:"favourites_count"`
	Id                 string  `json:"id"`
	InReplyToAccountId *string `json:"in_reply_to_account_id"`
	InReplyToId        *string `json:"in_reply_to_id"`
	Reblog             *Status `json:"reblog"`
	Reblogged          *bool   `json:"reblogged,omitempty"`
	ReblogsCount       int     `json:"reblogs_count"`
	RepliesCount       int     `json:"replies_count"`
	Uri                string  `json:"uri"`
}

// Webfinger defines model for Webfinger.
type Webfinger struct {
	Links   []WebfingerLinks `json:"links"`
	Subject string           `json:"subject"`
}

// WebfingerLinks defines model for WebfingerLinks.
type WebfingerLinks struct {
	Href string `json:"href"`
	Rel  string `json:"rel"`
	Type string `json:"type"`
}

// GetWellKnownWebfingerParams defines parameters for GetWellKnownWebfinger.
type GetWellKnownWebfingerParams struct {
	Resource string `form:"resource" json:"resource"`
}

// GetApiAccountsLookupParams defines parameters for GetApiAccountsLookup.
type GetApiAccountsLookupParams struct {
	Acct string `form:"acct" json:"acct"`
}

// PostApiStatusesJSONBody defines parameters for PostApiStatuses.
type PostApiStatusesJSONBody struct {
	InReplyToId *string `json:"in_reply_to_id"`
	Status      string  `json:"status"`
}

// PostApiStatusesJSONRequestBody defines body for PostApiStatuses for application/json ContentType.
type PostApiStatusesJSONRequestBody PostApiStatusesJSONBody

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthForm

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = AuthForm

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Webfinger lookuped account.
	// (GET /.well-known/webfinger)
	GetWellKnownWebfinger(w http.ResponseWriter, r *http.Request, params GetWellKnownWebfingerParams)
	// Lookup a username to see if it is available.
	// (GET /api/accounts/lookup)
	GetApiAccountsLookup(w http.ResponseWriter, r *http.Request, params GetApiAccountsLookupParams)
	// View information about a profile.
	// (GET /api/accounts/{id})
	GetApiAccountsId(w http.ResponseWriter, r *http.Request, id string)
	// Follow the given account.
	// (POST /api/accounts/{id}/follow)
	PostApiAccountsIdFollow(w http.ResponseWriter, r *http.Request, id string)
	// Accounts which follow the given account.
	// (GET /api/accounts/{id}/followers)
	GetApiAccountsIdFollowers(w http.ResponseWriter, r *http.Request, id string)
	// Accounts which the given account is following.
	// (GET /api/accounts/{id}/following)
	GetApiAccountsIdFollowing(w http.ResponseWriter, r *http.Request, id string)
	// Statuses posted to the given account.
	// (GET /api/accounts/{id}/statuses)
	GetApiAccountsIdStatuses(w http.ResponseWriter, r *http.Request, id string)
	// Unfollow the given account.
	// (POST /api/accounts/{id}/unfollow)
	PostApiAccountsIdUnfollow(w http.ResponseWriter, r *http.Request, id string)
	// Publish a status with the given parameters.
	// (POST /api/statuses)
	PostApiStatuses(w http.ResponseWriter, r *http.Request)
	// Obtain information about a status.
	// (GET /api/statuses/{id})
	GetApiStatusesId(w http.ResponseWriter, r *http.Request, id string)
	// Add a status to your favourites list.
	// (POST /api/statuses/{id}/favourite)
	PostApiStatusesIdFavourite(w http.ResponseWriter, r *http.Request, id string)
	// Reshare a status on your own profile.
	// (POST /api/statuses/{id}/reblog)
	PostApiStatusesIdReblog(w http.ResponseWriter, r *http.Request, id string)
	// Get a post's comments by ID
	// (GET /api/statuses/{id}/replies)
	GetApiStatusesIdReplies(w http.ResponseWriter, r *http.Request, id string)
	// Remove a status from your favourites list.
	// (POST /api/statuses/{id}/unfavourite)
	PostApiStatusesIdUnfavourite(w http.ResponseWriter, r *http.Request, id string)
	// Undo a reshare of a status.
	// (POST /api/statuses/{id}/unreblog)
	PostApiStatusesIdUnreblog(w http.ResponseWriter, r *http.Request, id string)
	// View statuses liked by logged in user.
	// (GET /api/timelines/favourite)
	GetApiTimelinesFavourite(w http.ResponseWriter, r *http.Request)
	// View statuses from followed users.
	// (GET /api/timelines/home)
	GetApiTimelinesHome(w http.ResponseWriter, r *http.Request)
	// Login the user
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Register the user
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Webfinger lookuped account.
// (GET /.well-known/webfinger)
func (_ Unimplemented) GetWellKnownWebfinger(w http.ResponseWriter, r *http.Request, params GetWellKnownWebfingerParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Lookup a username to see if it is available.
// (GET /api/accounts/lookup)
func (_ Unimplemented) GetApiAccountsLookup(w http.ResponseWriter, r *http.Request, params GetApiAccountsLookupParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// View information about a profile.
// (GET /api/accounts/{id})
func (_ Unimplemented) GetApiAccountsId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Follow the given account.
// (POST /api/accounts/{id}/follow)
func (_ Unimplemented) PostApiAccountsIdFollow(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Accounts which follow the given account.
// (GET /api/accounts/{id}/followers)
func (_ Unimplemented) GetApiAccountsIdFollowers(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Accounts which the given account is following.
// (GET /api/accounts/{id}/following)
func (_ Unimplemented) GetApiAccountsIdFollowing(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Statuses posted to the given account.
// (GET /api/accounts/{id}/statuses)
func (_ Unimplemented) GetApiAccountsIdStatuses(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unfollow the given account.
// (POST /api/accounts/{id}/unfollow)
func (_ Unimplemented) PostApiAccountsIdUnfollow(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Publish a status with the given parameters.
// (POST /api/statuses)
func (_ Unimplemented) PostApiStatuses(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Obtain information about a status.
// (GET /api/statuses/{id})
func (_ Unimplemented) GetApiStatusesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a status to your favourites list.
// (POST /api/statuses/{id}/favourite)
func (_ Unimplemented) PostApiStatusesIdFavourite(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reshare a status on your own profile.
// (POST /api/statuses/{id}/reblog)
func (_ Unimplemented) PostApiStatusesIdReblog(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a post's comments by ID
// (GET /api/statuses/{id}/replies)
func (_ Unimplemented) GetApiStatusesIdReplies(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a status from your favourites list.
// (POST /api/statuses/{id}/unfavourite)
func (_ Unimplemented) PostApiStatusesIdUnfavourite(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Undo a reshare of a status.
// (POST /api/statuses/{id}/unreblog)
func (_ Unimplemented) PostApiStatusesIdUnreblog(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// View statuses liked by logged in user.
// (GET /api/timelines/favourite)
func (_ Unimplemented) GetApiTimelinesFavourite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// View statuses from followed users.
// (GET /api/timelines/home)
func (_ Unimplemented) GetApiTimelinesHome(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login the user
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register the user
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetWellKnownWebfinger operation middleware
func (siw *ServerInterfaceWrapper) GetWellKnownWebfinger(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWellKnownWebfingerParams

	// ------------- Required query parameter "resource" -------------

	if paramValue := r.URL.Query().Get("resource"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resource"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "resource", r.URL.Query(), &params.Resource)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWellKnownWebfinger(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAccountsLookup operation middleware
func (siw *ServerInterfaceWrapper) GetApiAccountsLookup(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiAccountsLookupParams

	// ------------- Required query parameter "acct" -------------

	if paramValue := r.URL.Query().Get("acct"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "acct"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "acct", r.URL.Query(), &params.Acct)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "acct", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAccountsLookup(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAccountsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiAccountsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAccountsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiAccountsIdFollow operation middleware
func (siw *ServerInterfaceWrapper) PostApiAccountsIdFollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiAccountsIdFollow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAccountsIdFollowers operation middleware
func (siw *ServerInterfaceWrapper) GetApiAccountsIdFollowers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAccountsIdFollowers(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAccountsIdFollowing operation middleware
func (siw *ServerInterfaceWrapper) GetApiAccountsIdFollowing(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAccountsIdFollowing(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAccountsIdStatuses operation middleware
func (siw *ServerInterfaceWrapper) GetApiAccountsIdStatuses(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAccountsIdStatuses(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiAccountsIdUnfollow operation middleware
func (siw *ServerInterfaceWrapper) PostApiAccountsIdUnfollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiAccountsIdUnfollow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiStatuses operation middleware
func (siw *ServerInterfaceWrapper) PostApiStatuses(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiStatuses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiStatusesId operation middleware
func (siw *ServerInterfaceWrapper) GetApiStatusesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiStatusesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiStatusesIdFavourite operation middleware
func (siw *ServerInterfaceWrapper) PostApiStatusesIdFavourite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiStatusesIdFavourite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiStatusesIdReblog operation middleware
func (siw *ServerInterfaceWrapper) PostApiStatusesIdReblog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiStatusesIdReblog(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiStatusesIdReplies operation middleware
func (siw *ServerInterfaceWrapper) GetApiStatusesIdReplies(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiStatusesIdReplies(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiStatusesIdUnfavourite operation middleware
func (siw *ServerInterfaceWrapper) PostApiStatusesIdUnfavourite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiStatusesIdUnfavourite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiStatusesIdUnreblog operation middleware
func (siw *ServerInterfaceWrapper) PostApiStatusesIdUnreblog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiStatusesIdUnreblog(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiTimelinesFavourite operation middleware
func (siw *ServerInterfaceWrapper) GetApiTimelinesFavourite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiTimelinesFavourite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiTimelinesHome operation middleware
func (siw *ServerInterfaceWrapper) GetApiTimelinesHome(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiTimelinesHome(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/.well-known/webfinger", wrapper.GetWellKnownWebfinger)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/accounts/lookup", wrapper.GetApiAccountsLookup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/accounts/{id}", wrapper.GetApiAccountsId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/accounts/{id}/follow", wrapper.PostApiAccountsIdFollow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/accounts/{id}/followers", wrapper.GetApiAccountsIdFollowers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/accounts/{id}/following", wrapper.GetApiAccountsIdFollowing)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/accounts/{id}/statuses", wrapper.GetApiAccountsIdStatuses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/accounts/{id}/unfollow", wrapper.PostApiAccountsIdUnfollow)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/statuses", wrapper.PostApiStatuses)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/statuses/{id}", wrapper.GetApiStatusesId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/statuses/{id}/favourite", wrapper.PostApiStatusesIdFavourite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/statuses/{id}/reblog", wrapper.PostApiStatusesIdReblog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/statuses/{id}/replies", wrapper.GetApiStatusesIdReplies)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/statuses/{id}/unfavourite", wrapper.PostApiStatusesIdUnfavourite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/statuses/{id}/unreblog", wrapper.PostApiStatusesIdUnreblog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/timelines/favourite", wrapper.GetApiTimelinesFavourite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/timelines/home", wrapper.GetApiTimelinesHome)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yZS2/jNhCA/wrBFuihapS2N9+8KLJ1N0CCZNMcgsCgpJHEhCK1fMQwDP/3gqRetmVZ",
	"drHNutibJc2QM988+PAKx6IoBQeuFZ6ssIpzKIj7OY1jYbi2P0spSpCagvtA4ti91csS8AQrLSnP8DrA",
	"CVUlI8s5JwX0CqSCMbEAqebN0JUM5RoykK0Q5dmQEE16JzCS9b9XIPdYtQ6whC+GSkjw5MkO3BEPvLNb",
	"rvl5dt3Ztf05qKcT0QvE2toyNTq/ErLYBVsSpRZCJv/ShY71zYh9htxroo2bmBvGSMQAT7Q0EOzGuw7E",
	"jxJSPME/hG3WhFXKhHW+rAMcC66B9ydJSt6EkVRD181ICAaEb3xXJ8Sf8rmEki3nWswrs+dedNvFQdWR",
	"KhIiJrJDXCrMjXy2z3P/edBtayEdJmMkHZvlkuI2Vtvz90Rie/4daHsD0LAKmmzqy8hHiFLKrSM7tcEo",
	"f3U/qIZCHWLeDHTt1NbNXERKsrTPyvhZD6KqBYPKhEG7r2srN43Pnamrvgzq71f+xSHTrHYlG/g5do2z",
	"rkJsw7i8t3C8QR+ASJC2E9mnyD3ZnkQ0nuC/Hj/jwK8EdiQvi5uRc61LvF67kkmF1bcpRBxLuwiAiiUt",
	"NRXcKguZoZsS+PR2hlQJMU1pTNzHAGuqGdRC09sZDvAbSOU1Ly8uL361LEQJnJQUT/Dv7pXtajp3boQX",
	"C2Dsl1cuFjxcdJMnAxdaGwQ32yzBE/wR9CMw9smKt6lmx5OkAA1S4cnTClM7/RcDcokD7FsulqCEkTHg",
	"bgR8W/A51xetZyusSsGVp/7b5WWNq+qOpCxZxSN8kcnPL8r6vuqMOSrLfTg2yd988sE3RUHkEk/aJEVM",
	"iFdTQoKqWrxwkiEpaVi9UaGXGUI5LWnV8tW1Fx5FslpQvxrFowg2a9YIft5JRFC9viItkAJANEVUI6oQ",
	"eSPUrRh9QFc0WY/EOUv2oLSJ35Ks+uq5cfybwgLZ1mHbDRUckUgYjQgqpUjpfnih31y57ipUD8RboTYp",
	"XnmF/45lv+dV+3VTdxvv07MdpwXjzUU6B5TRN+BD5dkB4rwamVdXjcY3mGCjVvbOLnNzSR+ReTUHtMhp",
	"nKP0NN7W2eN4W43vvHdB257ZMN1LXbn9M4xP8vta4VyZtyeGscjHtpgaDbIdFBK7go1Pf8OP7sAPtcq5",
	"9ODa4EEs3YwcBNHJROsXKP1BJMujEmbzIHHCIVU1p/wD5xwvt3Om6zlSrLfDtP4aobg1EaMqRwR509CC",
	"6m4TaROqJzRjtlt1dM5vu1U3iN2G0Hw5AvRNpAnlvVsyj3Mf37C5IRhdCbPkqtF5r57gbUHtRdTFcbym",
	"SdImpRZoKYxsR1OIUaX3ImvvjEbyuqsvTt4VVk4UigA4au+wjmJ2ByonElpugntuYsF7Nv7bzNyt0+hy",
	"vqvkv6//22H4CO6gJZT+SaFYFIWdF0VLNPtjH3zDT6nyh47WO6dux4FjK/0OCvHWSdpUiuK4cjf86IJ/",
	"4PKbKHnDI+F2icfuoBKBCJJVwYu0bxnRtABGOajNJWSguj/XGt3145xL0V2D1MmCGH2FxBaib66IcnfN",
	"1IssF8VoWn+K4v8FypVgdfGROEZNXhmdh0xklB8oNqPzayd2+q588MRc/7936kb53sQxKJUaxpZI0Yy7",
	"fNi5jcwod7thy6BDQEJGla7+QhmEcFdLnhEHU25xqJ3ooliv/wkAAP//CHAP6NceAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
