// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// WebFingerLink defines model for WebFingerLink.
type WebFingerLink struct {
	Href string `json:"href"`
	Rel  string `json:"rel"`
	Type string `json:"type"`
}

// WebFingerResponse defines model for WebFingerResponse.
type WebFingerResponse struct {
	Links   []WebFingerLink `json:"links"`
	Subject string          `json:"subject"`
}

// GetWellKnownWebfingerParams defines parameters for GetWellKnownWebfinger.
type GetWellKnownWebfingerParams struct {
	Resource string `form:"resource" json:"resource"`
}

// GetApiAccountsLookupParams defines parameters for GetApiAccountsLookup.
type GetApiAccountsLookupParams struct {
	Acct string `form:"acct" json:"acct"`
}
