// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

// NewPost defines model for NewPost.
type NewPost struct {
	Content string `json:"content"`
	UserID  int    `json:"userID"`
}

// Post defines model for Post.
type Post struct {
	CommentCount int       `json:"commentCount"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           int       `json:"id"`
	LikeCount    int       `json:"likeCount"`
	ShareCount   int       `json:"shareCount"`
	UpdatedAt    time.Time `json:"updatedAt"`
	UserID       int       `json:"userID"`
}

// UpdatePost defines model for UpdatePost.
type UpdatePost struct {
	Content *string `json:"content,omitempty"`
}

// PostApiPostsJSONRequestBody defines body for PostApiPosts for application/json ContentType.
type PostApiPostsJSONRequestBody = NewPost

// PutApiPostsIdJSONRequestBody defines body for PutApiPostsId for application/json ContentType.
type PutApiPostsIdJSONRequestBody = UpdatePost
