// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Comment defines model for Comment.
type Comment struct {
	UpdatedAt time.Time `json:"UpdatedAt"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	ParentID  int       `json:"parentID"`
	PostID    int       `json:"postID"`
	UserID    int       `json:"userID"`
}

// Like defines model for Like.
type Like struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	PostID    int       `json:"postID"`
	UserID    int       `json:"userID"`
}

// NewComment defines model for NewComment.
type NewComment struct {
	Content string `json:"content"`
	PostID  int    `json:"postID"`
	UserID  int    `json:"userID"`
}

// NewLike defines model for NewLike.
type NewLike struct {
	PostID int `json:"postID"`
	UserID int `json:"userID"`
}

// NewPost defines model for NewPost.
type NewPost struct {
	Content string `json:"content"`
	UserID  int    `json:"userID"`
}

// NewShare defines model for NewShare.
type NewShare struct {
	PostID int `json:"postID"`
	UserID int `json:"userID"`
}

// Post defines model for Post.
type Post struct {
	CommentCount int       `json:"commentCount"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           int       `json:"id"`
	LikeCount    int       `json:"likeCount"`
	ShareCount   int       `json:"shareCount"`
	UpdatedAt    time.Time `json:"updatedAt"`
	UserID       int       `json:"userID"`
	Username     *string   `json:"username,omitempty"`
}

// Share defines model for Share.
type Share struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	PostID    int       `json:"postID"`
	UserID    int       `json:"userID"`
}

// UpdatePost defines model for UpdatePost.
type UpdatePost struct {
	Content *string `json:"content,omitempty"`
}

// PostApiPostsJSONRequestBody defines body for PostApiPosts for application/json ContentType.
type PostApiPostsJSONRequestBody = NewPost

// PutApiPostsIdJSONRequestBody defines body for PutApiPostsId for application/json ContentType.
type PutApiPostsIdJSONRequestBody = UpdatePost

// PostApiPostsIdCommentsJSONRequestBody defines body for PostApiPostsIdComments for application/json ContentType.
type PostApiPostsIdCommentsJSONRequestBody = NewComment

// PostApiPostsIdLikesJSONRequestBody defines body for PostApiPostsIdLikes for application/json ContentType.
type PostApiPostsIdLikesJSONRequestBody = NewLike

// PostApiPostsIdSharesJSONRequestBody defines body for PostApiPostsIdShares for application/json ContentType.
type PostApiPostsIdSharesJSONRequestBody = NewShare
