// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

// Follower defines model for Follower.
type Follower struct {
	CreatedAt   time.Time `json:"createdAt"`
	FollowerID  int       `json:"followerID"`
	FollowingID int       `json:"followingID"`
	Id          int       `json:"id"`
}

// NewFollower defines model for NewFollower.
type NewFollower struct {
	FollowerID  int `json:"followerID"`
	FollowingID int `json:"followingID"`
}
