// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

// NewUser defines model for NewUser.
type NewUser struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// UpdateUser defines model for UpdateUser.
type UpdateUser struct {
	Bio     *string `json:"bio,omitempty"`
	IsAdmin *bool   `json:"isAdmin,omitempty"`
}

// User defines model for User.
type User struct {
	Bio            string    `json:"bio"`
	CreatedAt      time.Time `json:"createdAt"`
	FollowersCount int       `json:"followersCount"`
	FollowingCount int       `json:"followingCount"`
	Id             int       `json:"id"`
	IsAdmin        bool      `json:"isAdmin"`
	Origin         string    `json:"origin"`
	UpdatedAt      time.Time `json:"updatedAt"`
	Username       string    `json:"username"`
}

// PostApiUsersJSONRequestBody defines body for PostApiUsers for application/json ContentType.
type PostApiUsersJSONRequestBody = NewUser

// PutApiUsersIdJSONRequestBody defines body for PutApiUsersId for application/json ContentType.
type PutApiUsersIdJSONRequestBody = UpdateUser
