/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Borg API
 * Borg OpenAPI specification
 * OpenAPI spec version: 0.0.1
 */

export * from './newPost';
export * from './post';
export * from './updatePost';
