// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Comment struct {
	ID        int32
	PostID    int32
	UserID    int32
	Content   string
	ParentID  sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Follower struct {
	ID          int32
	FollowerID  int32
	FollowingID int32
	CreatedAt   sql.NullTime
}

type Like struct {
	ID        int32
	PostID    int32
	UserID    int32
	CreatedAt sql.NullTime
}

type Post struct {
	ID           int32
	UserID       int32
	Content      string
	LikeCount    sql.NullInt32
	ShareCount   sql.NullInt32
	CommentCount sql.NullInt32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Share struct {
	ID        int32
	PostID    int32
	UserID    int32
	CreatedAt sql.NullTime
}

type User struct {
	ID             int32
	Username       string
	PasswordHash   string
	Bio            sql.NullString
	FollowersCount sql.NullInt32
	FollowingCount sql.NullInt32
	IsAdmin        sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Origin         sql.NullString
}
