// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/rs/xid"
)

type Account struct {
	ID           xid.ID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Username     string
	Uri          string
	DisplayName  sql.NullString
	Domain       sql.NullString
	InboxUri     string
	OutboxUri    string
	FollowersUri string
	FollowingUri string
	Url          string
}

type Favourite struct {
	ID              xid.ID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Uri             string
	AccountID       xid.ID
	TargetAccountID xid.ID
	StatusID        xid.ID
	StatusUri       string
}

type Follow struct {
	ID              xid.ID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Uri             string
	AccountID       xid.ID
	TargetAccountID xid.ID
}

type FollowRequest struct {
	ID               xid.ID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Uri              string
	AccountID        xid.ID
	TargetAccountID  xid.ID
	TargetAccountUri string
}

type Status struct {
	ID                 xid.ID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Uri                string
	Url                string
	Local              sql.NullBool
	Content            sql.NullString
	AccountID          xid.ID
	AccountUri         string
	InReplyToID        *xid.ID
	InReplyToUri       sql.NullString
	InReplyToAccountID *xid.ID
	ReblogOfID         *xid.ID
	ReblogOfUri        sql.NullString
	ReblogOfAccountID  sql.NullString
}

type User struct {
	ID           xid.ID
	AccountID    xid.ID
	PasswordHash string
}
