// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const authData = `-- name: AuthData :one
SELECT a.id, u.password_hash FROM accounts a JOIN users u ON a.id = u.account_id WHERE a.username = $1
`

type AuthDataRow struct {
	ID           int32
	PasswordHash string
}

func (q *Queries) AuthData(ctx context.Context, username string) (AuthDataRow, error) {
	row := q.db.QueryRowContext(ctx, authData, username)
	var i AuthDataRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const createActor = `-- name: CreateActor :one
INSERT INTO accounts (
    username, uri, display_name, domain, inbox_uri, outbox_uri, url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, created_at, updated_at, username, uri, display_name, domain, inbox_uri, outbox_uri, followers_uri, following_uri, url
`

type CreateActorParams struct {
	Username    string
	Uri         string
	DisplayName sql.NullString
	Domain      sql.NullString
	InboxUri    string
	OutboxUri   string
	Url         string
}

func (q *Queries) CreateActor(ctx context.Context, arg CreateActorParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createActor,
		arg.Username,
		arg.Uri,
		arg.DisplayName,
		arg.Domain,
		arg.InboxUri,
		arg.OutboxUri,
		arg.Url,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Uri,
		&i.DisplayName,
		&i.Domain,
		&i.InboxUri,
		&i.OutboxUri,
		&i.FollowersUri,
		&i.FollowingUri,
		&i.Url,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    account_id, password_hash
) VALUES (
    $1, $2
)
`

type CreateUserParams struct {
	AccountID    int32
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.AccountID, arg.PasswordHash)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, created_at, updated_at, username, uri, display_name, domain, inbox_uri, outbox_uri, followers_uri, following_uri, url FROM accounts WHERE username = $1 AND domain = $2
`

type GetAccountParams struct {
	Username string
	Domain   sql.NullString
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, arg.Username, arg.Domain)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Uri,
		&i.DisplayName,
		&i.Domain,
		&i.InboxUri,
		&i.OutboxUri,
		&i.FollowersUri,
		&i.FollowingUri,
		&i.Url,
	)
	return i, err
}

const getActor = `-- name: GetActor :one
SELECT id, created_at, updated_at, username, uri, display_name, domain, inbox_uri, outbox_uri, followers_uri, following_uri, url FROM accounts WHERE username = $1 AND domain IS NULL
`

func (q *Queries) GetActor(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getActor, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Uri,
		&i.DisplayName,
		&i.Domain,
		&i.InboxUri,
		&i.OutboxUri,
		&i.FollowersUri,
		&i.FollowingUri,
		&i.Url,
	)
	return i, err
}

const getAllStatuses = `-- name: GetAllStatuses :many
SELECT s.id, s.created_at, s.updated_at, s.uri, s.url, s.local, s.content, s.account_id, s.in_reply_to_id, s.reblog_of_id, a.username 
FROM statuses s 
JOIN accounts a ON s.account_id = a.id 
ORDER BY s.created_at DESC
`

type GetAllStatusesRow struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Uri         string
	Url         string
	Local       sql.NullBool
	Content     string
	AccountID   int32
	InReplyToID sql.NullInt32
	ReblogOfID  sql.NullInt32
	Username    string
}

func (q *Queries) GetAllStatuses(ctx context.Context) ([]GetAllStatusesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllStatusesRow
	for rows.Next() {
		var i GetAllStatusesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uri,
			&i.Url,
			&i.Local,
			&i.Content,
			&i.AccountID,
			&i.InReplyToID,
			&i.ReblogOfID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
