// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const addStatus = `-- name: AddStatus :exec
INSERT INTO statuses (
    uri, url, content, account_id, in_reply_to_id, reblog_of_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type AddStatusParams struct {
	Uri         string
	Url         string
	Content     string
	AccountID   int32
	InReplyToID sql.NullInt32
	ReblogOfID  sql.NullInt32
}

func (q *Queries) AddStatus(ctx context.Context, arg AddStatusParams) error {
	_, err := q.db.ExecContext(ctx, addStatus,
		arg.Uri,
		arg.Url,
		arg.Content,
		arg.AccountID,
		arg.InReplyToID,
		arg.ReblogOfID,
	)
	return err
}

const authData = `-- name: AuthData :one
SELECT a.id, u.password_hash FROM accounts a JOIN users u ON a.id = u.account_id WHERE a.username = $1
`

type AuthDataRow struct {
	ID           int32
	PasswordHash string
}

func (q *Queries) AuthData(ctx context.Context, username string) (AuthDataRow, error) {
	row := q.db.QueryRowContext(ctx, authData, username)
	var i AuthDataRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const createActor = `-- name: CreateActor :one
INSERT INTO accounts (
    username, uri, display_name, domain, inbox_uri, outbox_uri, url, followers_uri, following_uri
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, created_at, updated_at, username, uri, display_name, domain, inbox_uri, outbox_uri, followers_uri, following_uri, url
`

type CreateActorParams struct {
	Username     string
	Uri          string
	DisplayName  sql.NullString
	Domain       sql.NullString
	InboxUri     string
	OutboxUri    string
	Url          string
	FollowersUri string
	FollowingUri string
}

func (q *Queries) CreateActor(ctx context.Context, arg CreateActorParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createActor,
		arg.Username,
		arg.Uri,
		arg.DisplayName,
		arg.Domain,
		arg.InboxUri,
		arg.OutboxUri,
		arg.Url,
		arg.FollowersUri,
		arg.FollowingUri,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Uri,
		&i.DisplayName,
		&i.Domain,
		&i.InboxUri,
		&i.OutboxUri,
		&i.FollowersUri,
		&i.FollowingUri,
		&i.Url,
	)
	return i, err
}

const createFavourite = `-- name: CreateFavourite :one
INSERT INTO favourites (
    account_id, 
    status_id,
    uri
) VALUES (
    $1, $2, $3
)
RETURNING id, created_at, updated_at, uri, account_id, status_id
`

type CreateFavouriteParams struct {
	AccountID int32
	StatusID  int32
	Uri       string
}

func (q *Queries) CreateFavourite(ctx context.Context, arg CreateFavouriteParams) (Favourite, error) {
	row := q.db.QueryRowContext(ctx, createFavourite, arg.AccountID, arg.StatusID, arg.Uri)
	var i Favourite
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uri,
		&i.AccountID,
		&i.StatusID,
	)
	return i, err
}

const createFollow = `-- name: CreateFollow :one
INSERT INTO follows (
    uri, account_id, target_account_id
) VALUES (
    $1, $2, $3
) ON CONFLICT (account_id, target_account_id) 
DO UPDATE SET 
    uri = EXCLUDED.uri,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, created_at, updated_at, uri, account_id, target_account_id
`

type CreateFollowParams struct {
	Uri             string
	AccountID       int32
	TargetAccountID int32
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) (Follow, error) {
	row := q.db.QueryRowContext(ctx, createFollow, arg.Uri, arg.AccountID, arg.TargetAccountID)
	var i Follow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uri,
		&i.AccountID,
		&i.TargetAccountID,
	)
	return i, err
}

const createFollowRequest = `-- name: CreateFollowRequest :exec
INSERT INTO follow_requests (
    uri, account_id, target_account_id
) VALUES (
    $1, $2, $3
)
`

type CreateFollowRequestParams struct {
	Uri             string
	AccountID       int32
	TargetAccountID int32
}

func (q *Queries) CreateFollowRequest(ctx context.Context, arg CreateFollowRequestParams) error {
	_, err := q.db.ExecContext(ctx, createFollowRequest, arg.Uri, arg.AccountID, arg.TargetAccountID)
	return err
}

const createStatus = `-- name: CreateStatus :one
INSERT INTO statuses (
    url, local, content, account_id, in_reply_to_id, reblog_of_id, uri
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, created_at, updated_at, uri, url, local, content, account_id, in_reply_to_id, reblog_of_id
`

type CreateStatusParams struct {
	Url         string
	Local       sql.NullBool
	Content     string
	AccountID   int32
	InReplyToID sql.NullInt32
	ReblogOfID  sql.NullInt32
	Uri         string
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (Status, error) {
	row := q.db.QueryRowContext(ctx, createStatus,
		arg.Url,
		arg.Local,
		arg.Content,
		arg.AccountID,
		arg.InReplyToID,
		arg.ReblogOfID,
		arg.Uri,
	)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uri,
		&i.Url,
		&i.Local,
		&i.Content,
		&i.AccountID,
		&i.InReplyToID,
		&i.ReblogOfID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    account_id, password_hash
) VALUES (
    $1, $2
)
`

type CreateUserParams struct {
	AccountID    int32
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.AccountID, arg.PasswordHash)
	return err
}

const deleteFavouriteByID = `-- name: DeleteFavouriteByID :exec
DELETE FROM favourites WHERE id = $1
`

func (q *Queries) DeleteFavouriteByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFavouriteByID, id)
	return err
}

const deleteStatusByID = `-- name: DeleteStatusByID :exec
DELETE FROM statuses WHERE id = $1
`

func (q *Queries) DeleteStatusByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteStatusByID, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, created_at, updated_at, username, uri, display_name, domain, inbox_uri, outbox_uri, followers_uri, following_uri, url FROM accounts WHERE username = $1 AND domain = $2
`

type GetAccountParams struct {
	Username string
	Domain   sql.NullString
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, arg.Username, arg.Domain)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Uri,
		&i.DisplayName,
		&i.Domain,
		&i.InboxUri,
		&i.OutboxUri,
		&i.FollowersUri,
		&i.FollowingUri,
		&i.Url,
	)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, created_at, updated_at, username, uri, display_name, domain, inbox_uri, outbox_uri, followers_uri, following_uri, url FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountById(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Uri,
		&i.DisplayName,
		&i.Domain,
		&i.InboxUri,
		&i.OutboxUri,
		&i.FollowersUri,
		&i.FollowingUri,
		&i.Url,
	)
	return i, err
}

const getAccountFollowers = `-- name: GetAccountFollowers :many
SELECT a.id, a.created_at, a.updated_at, a.username, a.uri, a.display_name, a.domain, a.inbox_uri, a.outbox_uri, a.followers_uri, a.following_uri, a.url FROM accounts a
JOIN follows f ON a.id = f.account_id
WHERE f.target_account_id = $1
`

func (q *Queries) GetAccountFollowers(ctx context.Context, targetAccountID int32) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccountFollowers, targetAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Uri,
			&i.DisplayName,
			&i.Domain,
			&i.InboxUri,
			&i.OutboxUri,
			&i.FollowersUri,
			&i.FollowingUri,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountFollowing = `-- name: GetAccountFollowing :many
SELECT a.id, a.created_at, a.updated_at, a.username, a.uri, a.display_name, a.domain, a.inbox_uri, a.outbox_uri, a.followers_uri, a.following_uri, a.url FROM accounts a
JOIN follows f ON a.id = f.target_account_id
WHERE f.account_id = $1
`

func (q *Queries) GetAccountFollowing(ctx context.Context, accountID int32) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccountFollowing, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Uri,
			&i.DisplayName,
			&i.Domain,
			&i.InboxUri,
			&i.OutboxUri,
			&i.FollowersUri,
			&i.FollowingUri,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActor = `-- name: GetActor :one
SELECT id, created_at, updated_at, username, uri, display_name, domain, inbox_uri, outbox_uri, followers_uri, following_uri, url FROM accounts WHERE username = $1 AND domain IS NULL
`

func (q *Queries) GetActor(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getActor, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Uri,
		&i.DisplayName,
		&i.Domain,
		&i.InboxUri,
		&i.OutboxUri,
		&i.FollowersUri,
		&i.FollowingUri,
		&i.Url,
	)
	return i, err
}

const getActorByURI = `-- name: GetActorByURI :one
SELECT id, created_at, updated_at, username, uri, display_name, domain, inbox_uri, outbox_uri, followers_uri, following_uri, url FROM accounts WHERE uri = $1
`

func (q *Queries) GetActorByURI(ctx context.Context, uri string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getActorByURI, uri)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Uri,
		&i.DisplayName,
		&i.Domain,
		&i.InboxUri,
		&i.OutboxUri,
		&i.FollowersUri,
		&i.FollowingUri,
		&i.Url,
	)
	return i, err
}

const getFavouriteByURI = `-- name: GetFavouriteByURI :one
SELECT id, created_at, updated_at, uri, account_id, status_id FROM favourites WHERE uri = $1
`

func (q *Queries) GetFavouriteByURI(ctx context.Context, uri string) (Favourite, error) {
	row := q.db.QueryRowContext(ctx, getFavouriteByURI, uri)
	var i Favourite
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uri,
		&i.AccountID,
		&i.StatusID,
	)
	return i, err
}

const getFollowerCollection = `-- name: GetFollowerCollection :one
SELECT 
    (SELECT followers_uri FROM accounts a WHERE a.username = $1),
    (SELECT COUNT(*) FROM follows f JOIN accounts a ON f.target_account_id = a.id WHERE a.username = $1)
`

type GetFollowerCollectionRow struct {
	FollowersUri string
	Count        int64
}

func (q *Queries) GetFollowerCollection(ctx context.Context, username string) (GetFollowerCollectionRow, error) {
	row := q.db.QueryRowContext(ctx, getFollowerCollection, username)
	var i GetFollowerCollectionRow
	err := row.Scan(&i.FollowersUri, &i.Count)
	return i, err
}

const getFollowingCollection = `-- name: GetFollowingCollection :one
SELECT 
    (SELECT following_uri FROM accounts a WHERE a.username = $1),
    (SELECT COUNT(*) FROM follows f JOIN accounts a ON f.account_id = a.id WHERE a.username = $1)
`

type GetFollowingCollectionRow struct {
	FollowingUri string
	Count        int64
}

func (q *Queries) GetFollowingCollection(ctx context.Context, username string) (GetFollowingCollectionRow, error) {
	row := q.db.QueryRowContext(ctx, getFollowingCollection, username)
	var i GetFollowingCollectionRow
	err := row.Scan(&i.FollowingUri, &i.Count)
	return i, err
}

const getLocalStatuses = `-- name: GetLocalStatuses :many
SELECT 
    s.id, s.created_at, s.updated_at, s.uri, s.url, s.local, s.content, s.account_id, s.in_reply_to_id, s.reblog_of_id,
    a.id, a.created_at, a.updated_at, a.username, a.uri, a.display_name, a.domain, a.inbox_uri, a.outbox_uri, a.followers_uri, a.following_uri, a.url,
    (SELECT COUNT(*) FROM favourites f WHERE f.status_id = s.id) AS like_count,
    (SELECT COUNT(*) FROM statuses r WHERE r.in_reply_to_id = s.id) AS comment_count,
    (SELECT COUNT(*) FROM statuses b WHERE b.reblog_of_id = s.id) AS share_count
FROM statuses s
JOIN accounts a ON s.account_id = a.id
WHERE a.domain is null and s.in_reply_to_id is null
`

type GetLocalStatusesRow struct {
	Status       Status
	Account      Account
	LikeCount    int64
	CommentCount int64
	ShareCount   int64
}

func (q *Queries) GetLocalStatuses(ctx context.Context) ([]GetLocalStatusesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLocalStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocalStatusesRow
	for rows.Next() {
		var i GetLocalStatusesRow
		if err := rows.Scan(
			&i.Status.ID,
			&i.Status.CreatedAt,
			&i.Status.UpdatedAt,
			&i.Status.Uri,
			&i.Status.Url,
			&i.Status.Local,
			&i.Status.Content,
			&i.Status.AccountID,
			&i.Status.InReplyToID,
			&i.Status.ReblogOfID,
			&i.Account.ID,
			&i.Account.CreatedAt,
			&i.Account.UpdatedAt,
			&i.Account.Username,
			&i.Account.Uri,
			&i.Account.DisplayName,
			&i.Account.Domain,
			&i.Account.InboxUri,
			&i.Account.OutboxUri,
			&i.Account.FollowersUri,
			&i.Account.FollowingUri,
			&i.Account.Url,
			&i.LikeCount,
			&i.CommentCount,
			&i.ShareCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusById = `-- name: GetStatusById :one
SELECT id, created_at, updated_at, uri, url, local, content, account_id, in_reply_to_id, reblog_of_id FROM statuses WHERE id = $1
`

func (q *Queries) GetStatusById(ctx context.Context, id int32) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatusById, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uri,
		&i.Url,
		&i.Local,
		&i.Content,
		&i.AccountID,
		&i.InReplyToID,
		&i.ReblogOfID,
	)
	return i, err
}

const getStatusByIdWithMetadata = `-- name: GetStatusByIdWithMetadata :one
SELECT 
    s.id, s.created_at, s.updated_at, s.uri, s.url, s.local, s.content, s.account_id, s.in_reply_to_id, s.reblog_of_id,
    a.id, a.created_at, a.updated_at, a.username, a.uri, a.display_name, a.domain, a.inbox_uri, a.outbox_uri, a.followers_uri, a.following_uri, a.url,
    (SELECT COUNT(*) FROM favourites f WHERE f.status_id = s.id) AS like_count,
    (SELECT COUNT(*) FROM statuses r WHERE r.in_reply_to_id = s.id) AS comment_count,
    (SELECT COUNT(*) FROM statuses b WHERE b.reblog_of_id = s.id) AS share_count
FROM statuses s
JOIN accounts a ON s.account_id = a.id
WHERE s.id = $1
`

type GetStatusByIdWithMetadataRow struct {
	Status       Status
	Account      Account
	LikeCount    int64
	CommentCount int64
	ShareCount   int64
}

func (q *Queries) GetStatusByIdWithMetadata(ctx context.Context, id int32) (GetStatusByIdWithMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getStatusByIdWithMetadata, id)
	var i GetStatusByIdWithMetadataRow
	err := row.Scan(
		&i.Status.ID,
		&i.Status.CreatedAt,
		&i.Status.UpdatedAt,
		&i.Status.Uri,
		&i.Status.Url,
		&i.Status.Local,
		&i.Status.Content,
		&i.Status.AccountID,
		&i.Status.InReplyToID,
		&i.Status.ReblogOfID,
		&i.Account.ID,
		&i.Account.CreatedAt,
		&i.Account.UpdatedAt,
		&i.Account.Username,
		&i.Account.Uri,
		&i.Account.DisplayName,
		&i.Account.Domain,
		&i.Account.InboxUri,
		&i.Account.OutboxUri,
		&i.Account.FollowersUri,
		&i.Account.FollowingUri,
		&i.Account.Url,
		&i.LikeCount,
		&i.CommentCount,
		&i.ShareCount,
	)
	return i, err
}

const getStatusByURI = `-- name: GetStatusByURI :one
SELECT id, created_at, updated_at, uri, url, local, content, account_id, in_reply_to_id, reblog_of_id FROM statuses WHERE uri = $1
`

func (q *Queries) GetStatusByURI(ctx context.Context, uri string) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatusByURI, uri)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uri,
		&i.Url,
		&i.Local,
		&i.Content,
		&i.AccountID,
		&i.InReplyToID,
		&i.ReblogOfID,
	)
	return i, err
}

const getStatusFavourites = `-- name: GetStatusFavourites :many
SELECT id, created_at, updated_at, uri, account_id, status_id
FROM favourites
WHERE status_id = $1
`

func (q *Queries) GetStatusFavourites(ctx context.Context, statusID int32) ([]Favourite, error) {
	rows, err := q.db.QueryContext(ctx, getStatusFavourites, statusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Favourite
	for rows.Next() {
		var i Favourite
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uri,
			&i.AccountID,
			&i.StatusID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusShares = `-- name: GetStatusShares :many
SELECT id, created_at, updated_at, uri, url, local, content, account_id, in_reply_to_id, reblog_of_id
FROM statuses 
WHERE reblog_of_id = $1
`

func (q *Queries) GetStatusShares(ctx context.Context, reblogOfID sql.NullInt32) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, getStatusShares, reblogOfID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uri,
			&i.Url,
			&i.Local,
			&i.Content,
			&i.AccountID,
			&i.InReplyToID,
			&i.ReblogOfID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusesByAccountId = `-- name: GetStatusesByAccountId :many
SELECT 
    s.id, s.created_at, s.updated_at, s.uri, s.url, s.local, s.content, s.account_id, s.in_reply_to_id, s.reblog_of_id,
    a.id, a.created_at, a.updated_at, a.username, a.uri, a.display_name, a.domain, a.inbox_uri, a.outbox_uri, a.followers_uri, a.following_uri, a.url,
    (SELECT COUNT(*) FROM favourites f WHERE f.status_id = s.id) AS like_count,
    (SELECT COUNT(*) FROM statuses r WHERE r.in_reply_to_id = s.id) AS comment_count,
    (SELECT COUNT(*) FROM statuses b WHERE b.reblog_of_id = s.id) AS share_count
FROM statuses s
JOIN accounts a ON s.account_id = a.id
WHERE s.account_id = $1
`

type GetStatusesByAccountIdRow struct {
	Status       Status
	Account      Account
	LikeCount    int64
	CommentCount int64
	ShareCount   int64
}

func (q *Queries) GetStatusesByAccountId(ctx context.Context, accountID int32) ([]GetStatusesByAccountIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getStatusesByAccountId, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatusesByAccountIdRow
	for rows.Next() {
		var i GetStatusesByAccountIdRow
		if err := rows.Scan(
			&i.Status.ID,
			&i.Status.CreatedAt,
			&i.Status.UpdatedAt,
			&i.Status.Uri,
			&i.Status.Url,
			&i.Status.Local,
			&i.Status.Content,
			&i.Status.AccountID,
			&i.Status.InReplyToID,
			&i.Status.ReblogOfID,
			&i.Account.ID,
			&i.Account.CreatedAt,
			&i.Account.UpdatedAt,
			&i.Account.Username,
			&i.Account.Uri,
			&i.Account.DisplayName,
			&i.Account.Domain,
			&i.Account.InboxUri,
			&i.Account.OutboxUri,
			&i.Account.FollowersUri,
			&i.Account.FollowingUri,
			&i.Account.Url,
			&i.LikeCount,
			&i.CommentCount,
			&i.ShareCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
