openapi: 3.0.1
info:
  title: Dev API
  version: 0.0.1
  description: Staging changes
  contact: {}

paths:
  /foo:
    get:
      summary: bar
      responses:
        "200":
          description: OK
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
      bearerFormat: JWT
