openapi: 3.0.1
info:
  title: Borg API
  version: 0.0.1
  description: Borg OpenAPI specification
  contact: {}

paths:
  /.well-known/webfinger:
    get:
      summary: Webfinger lookuped account.
      parameters:
        - name: resource
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/jrd+json:
              schema:
                $ref: "#/components/schemas/Webfinger"
  /api/accounts/{id}:
    get:
      summary: View information about a profile.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
  /api/accounts/{id}/statuses:
    get:
      summary: Statuses posted to the given account.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Status"
      security:
        - BearerAuth: []
  /api/accounts/{id}/followers:
    get:
      summary: Accounts which follow the given account.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
  /api/accounts/{id}/following:
    get:
      summary: Accounts which the given account is following.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
  /api/accounts/{id}/follow:
    post:
      summary: Follow the given account.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
      security:
        - BearerAuth: []
  /api/accounts/{id}/unfollow:
    post:
      summary: Unfollow the given account.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
      security:
        - BearerAuth: []
  /api/accounts/lookup:
    get:
      summary: Lookup a username to see if it is available.
      parameters:
        - name: acct
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
  /api/statuses:
    post:
      summary: Publish a status with the given parameters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
                - in_reply_to_id
              properties:
                status:
                  type: string
                in_reply_to_id:
                  type: string
                  nullable: true
      responses:
        "200":
          description: OK
      security:
        - BearerAuth: []
  /api/statuses/{id}:
    get:
      summary: Obtain information about a status.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Status"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
      security:
        - BearerAuth: []
  /api/statuses/{id}/favourite:
    post:
      summary: Add a status to your favourites list.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Status favourited.
      security:
        - BearerAuth: []
  /api/statuses/{id}/unfavourite:
    post:
      summary: Remove a status from your favourites list.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Status unfavourited.
      security:
        - BearerAuth: []
  /api/statuses/{id}/reblog:
    post:
      summary: Reshare a status on your own profile.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Status has been reblogged
      security:
        - BearerAuth: []
  /api/statuses/{id}/unreblog:
    post:
      summary: Undo a reshare of a status.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Status unboosted
      security:
        - BearerAuth: []
  /api/statuses/{id}/replies:
    get:
      summary: Get a post's comments by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Status"
      security:
        - BearerAuth: []
  /api/timelines/home:
    get:
      summary: View statuses from followed users.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Status"
      security:
        - BearerAuth: []
  /api/timelines/favourite:
    get:
      summary: View statuses liked by logged in user.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Status"
      security:
        - BearerAuth: []
  /auth/login:
    post:
      summary: Login the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthForm"
      responses:
        "200":
          description: Successfully signed in
  /auth/register:
    post:
      summary: Register the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthForm"
      responses:
        "200":
          description: Successfully signed up

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
      bearerFormat: JWT
  schemas:
    Webfinger:
      type: object
      required:
        - subject
        - links
      properties:
        subject:
          type: string
        links:
          type: array
          items:
            $ref: "#/components/schemas/WebfingerLinks"
    WebfingerLinks:
      type: object
      required:
        - rel
        - type
        - href
      properties:
        rel:
          type: string
        type:
          type: string
        href:
          type: string
    Account:
      type: object
      required:
        - id
        - username
        - acct
        - display_name
        - url
        - followers_count
        - following_count
      properties:
        id:
          type: string
        username:
          type: string
        acct:
          type: string
        display_name:
          type: string
        url:
          type: string
        followers_count:
          type: integer
        following_count:
          type: integer
    Status:
      type: object
      nullable: true
      required:
        - id
        - uri
        - content
        - reblogs_count
        - favourites_count
        - replies_count
        - in_reply_to_id
        - in_reply_to_account_id
        - reblog
        - account
      properties:
        id:
          type: string
        uri:
          type: string
        content:
          type: string
        reblogs_count:
          type: integer
        favourites_count:
          type: integer
        replies_count:
          type: integer
        in_reply_to_id:
          type: string
          nullable: true
        in_reply_to_account_id:
          type: string
          nullable: true
        reblog:
          $ref: "#/components/schemas/Status"
        account:
          $ref: "#/components/schemas/Account"
        favourited:
          type: boolean
        reblogged:
          type: boolean
    AuthForm:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
